spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123

  liquibase:
    change-log: classpath:db/changelog-master.yml
    liquibase-schema: public
    enabled: true
telegram:
  bot:
    token: 6614391649:AAHS7jOXkTogeiJSF4NOk3z35UibSzA_YQs
    name: SheltersSkyProBot
